### ISSUE TITLE
"No such file or directory (os error 2)" when trying to start a Holochain process that points to a lair path that has whitespaces

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/lair#90]
Steps to reproduce:

1. In one terminal:

```bash
mkdir lair\ test
cd lair\ test/
lair-keystore init
lair-keystore server
```

2. In a second terminal:
2.1 Create a test folder.
2.2 Create a `conductor-config.yaml` in that folder with this content:
```yaml
---
environment_path: "/home/guillem/test"
keystore:
  type: lair_server
  connection_url: "unix:///home/guillem/lair%20test/socket?k=fehuRaXUayIOCf2XAY9KlObGHFdk-LWvq5HbDL18MXM"
dpki: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 24647
network:
  transport_pool:
    - type: proxy
      sub_transport:
        type: quic
        bind_to: ~
        override_host: ~
        override_port: ~
      proxy_config:
        type: remote_proxy_client
        proxy_url: "kitsune-proxy://f3gH2VMkJ4qvZJOXx0ccL_Zo5n-s_CnBjSzAsEHHDCA/kitsune-quic/h/137.184.142.208/p/5788/--"
  bootstrap_service: "https://bootstrap-staging.holo.host/"
  tuning_params:
  network_type: quic_bootstrap
db_sync_strategy: Fast

```
2.3 Run `holochain -c conductor-config.yaml`.
